# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170817_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=162),
        ),
    ]
