# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171023_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
